# .github/workflows/test-ci.yml
name: Scala CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # or the version you use

    - name: Install SBT
      run: |
        curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.6/sbt-1.9.6.deb
        sudo dpkg -i sbt.deb
        sudo apt-get update
        sudo apt-get install sbt

    - name: Run SBT Tests
      run: sbt test
