# .github/workflows/test.yml
name: Scala CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # JDK is LTS 16/07/24 at 17.0.12
        distribution: 'temurin'
        cache: 'sbt'
    - uses: olafurpg/setup-scala@v11
    - name: Compile
      run: sbt compile
    - name: Test
      run: sbt test